version: '3'

services:

  db:
    image: dimitriaugusto/mysql:prod
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network

  app:
    container_name: app
    image: dimitriaugusto/node:prod
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  nginx:
    image: dimitriaugusto/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge