version: '3'

services:

  app:
    build:
      context: node
      dockerfile: node/Dockerfile.prod
    container_name: app
    image: dimitriaugusto/node:prod
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    tty: true
#    ports:
#      - "8081:8080"
#    volumes:
#      - ./node/app:/usr/src/app
    depends_on:
      - db

  db:
    build:
      context: mysql
      dockerfile: mysql/Dockerfile.prod
    image: dimitriaugusto/mysql:prod
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
#    volumes:
#      - ./mysql/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
      dockerfile: nginx/Dockerfile
    container_name: nginx
    image: dimitriaugusto/nginx:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge